config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('messages/', include('messangerapp.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView,  ProfileUpdateView, ProfileView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('update-profile/', ProfileUpdateView.as_view(), name='update-profile'),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users_image/', blank=True, null=True, default='default_img/user_img.png')


    class Meta:
        db_table = 'custom_user'

    def __str__(self):
        return f"ID: {self.pk} | Username: {self.username}"


users/forms.py
from django import forms
from .models import CustomUser


class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'username', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('image', 'first_name', 'last_name', 'email', 'username')



users/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserForm, ProfileUpdateForm
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
# from products.models import Logo
# from products.models import Products
# Create your views here.


class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'register.html', context=context)


class LoginView(View):
    def get(self, request):
        create_form = AuthenticationForm()
        context = {
            'form': create_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect('message:user-list')
        else:

            context = {
                'form': login_form
            }
            return render(request, 'login.html', context=context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('users:login')


class ProfileView(View):
    def get(self, request):

        context = {
            'user': request.user,

        }
        return render(request, 'profile.html', context=context)


class ProfileUpdateView(View):
    def get(self, request):
        update_form = ProfileUpdateForm(instance=request.user)
        context = {
            'form': update_form
        }
        return render(request, 'profile_update.html', context=context)

    def post(self, request):
        update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            update_form.save()
            return redirect('users:profile')
        else:
            context = {
                'form': update_form
            }
            messages.error(request,'Something went wrong')
            return render(request, 'profile_update.html', context=context)

users/templates/login.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>Kirish sahifasi</title>
    <style>
    * {
        box-sizing: border-box;
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        margin: 0;
        padding: 0;
    }

    .container {
        width: 30%;
        margin: 100px auto;
        padding: 20px;
        background-color: #ffffff;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    h2 {
        text-align: center;
        color: #333;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        font-size: 14px;
        color: #555;
    }

    input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    button {
        width: 100%;
        padding: 12px;
        background-color: #007BFF;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #0056b3;
    }

    .link {
        text-align: center;
        margin-top: 10px;
    }

    .link a {
        color: #007BFF;
        text-decoration: none;
    }

    .link a:hover {
        text-decoration: underline;
    }
    </style>
</head>
<body>
    <div class="container">
        <h2>Kirish</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Foydalanuvchi nomi yoki Email:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Parol:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Kirish</button>
        </form>
        <div class="link">
            <a href="{% url 'users:register' %}">Ro'yxatdan o'tish</a>
        </div>
    </div>
</body>
</html>

users/templates/profile.html
{% extends 'base.html' %}
{% block title %}
  Profile
{% endblock %}

{% block content %}
<style>
  .profile-container {
    max-width: 400px;
    margin: 0 auto;
    text-align: center;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    background-color: #f9f9f9;
  }
  .profile-image {
    width: 150px;
    height: 150px;
    border-radius: 50%;
    object-fit: cover;
    margin-bottom: 20px;
  }
  .profile-info {
    margin: 10px 0;
  }
  .edit-button, .orders-button {
    display: inline-block;
    padding: 10px 20px;
    color: white;
    background-color: #8A2BE2;
    text-decoration: none;
    border: none;
    border-radius: 5px;
    margin: 10px 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }
  .edit-button:hover, .orders-button:hover {
    background-color: #4a148c;
  }
</style>

<div class="profile-container">
  <img src="{{ user.image.url }}" alt="User Image" class="profile-image">
  <h3 class="profile-username">Username: {{ user.username }}</h3>
  <h3 class="profile-info">First name: {{ user.first_name }}</h3>
  <h3 class="profile-info">Last name: {{ user.last_name }}</h3>
  <h3 class="profile-info">Email: {{ user.email }}</h3>
  <a href="{% url 'users:update-profile' %}">
    <button class="edit-button">Edit profile</button>

</div>

{% endblock content %}

users/templates/profile_update.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>Profilni Yangilash Sahifasi</title>
    <style>
    * {
        box-sizing: border-box;
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        margin: 0;
        padding: 0;
    }

    .container {
        width: 40%;
        margin: 100px auto;
        padding: 20px;
        background-color: #ffffff;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    h2 {
        text-align: center;
        color: #333;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        font-size: 14px;
        color: #555;
    }

    input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    button {
        width: 100%;
        padding: 12px;
        background-color: #4CAF50;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #45a049;
    }
    </style>
</head>
<body>
    <div class="container">
            <h2>Profilni Yangilash</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}<br>
                    <div class="au-input au-input--full">{{ field }}</div>
                    {% if field.help_text %}
                        <br><small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit">Yangilash</button>
        </form>
    </div>
</body>
</html>

users/templates/register.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>Ro'yxatga olish sahifasi</title>
    <style>
    * {
        box-sizing: border-box;
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        margin: 0;
        padding: 0;
    }

    .container {
        width: 40%;
        margin: 100px auto;
        padding: 20px;
        background-color: #ffffff;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    h2 {
        text-align: center;
        color: #333;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        font-size: 14px;
        color: #555;
    }

    input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    button {
        width: 100%;
        padding: 12px;
        background-color: #4CAF50;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #45a049;
    }
    </style>
</head>
<body>
    <div class="container">
        <h2>Ro'yxatga olish</h2>
        <form  method="post" enctype="multipart/form-data">
                {% csrf_token %}
            {% for field in form %}
                                <p >
                                    {{ field.label_tag }}<br>
                                    <div class="au-input au-input--full">{{ field }}</div>
                                    {% if field.help_text %}
                                        <br><small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                </p>
            {% endfor %}

<!--            {{ form.as_p }}-->
            <button type="submit">Ro'yxatdan o'tish</button>


        </form>
    </div>
</body>
</html>